[devops]
image=registry.fedoraproject.org/fedora-toolbox:latest
pull=true
init=false

init_hooks="sh /home/michaljanicki/.config/distrobox/scripts/setup-devops.sh"
exported_bins="/usr/bin/k9s /usr/bin/kubectl /usr/bin/gcloud usr/bin/helm usr/bin/terraform usr/bin/kubectl-auto-rollouts"

# [go]
# image=registry.fedoraproject.org/fedora-toolbox:latest
# pull=true
# init=false
#
# init_hooks="sh /home/michaljanicki/.config/distrobox/scripts/setup-go.sh"
# exported_bins="/usr/bin/go /usr/bin/gofmt"
