# EVERFOREST DARK MEDIUM PALETTE
$bg = rgb(2d353b)
$bg-alt = rgb(343f44)
$fg = rgb(d3c6aa)
$green = rgb(a6b46c)
$yellow = rgb(dbbc7f)
$red = rgb(e67e80)
$blue = rgb(7fbbb3)
$purple = rgb(d699b6)

# FONT
$font = Meslo NF Regular

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
}

# BACKGROUND
background {
    monitor =
    path = ~/.local/share/wallpapers/forest1.jpg
    blur_passes = 1
    color = $bg
}

# TIME
label {
    monitor = DP-1
    text = cmd[update:30000] echo "$(date +"%R")"
    color = $fg
    font_size = 90
    font_family = $font
    position = -30, 0
    halign = right
    valign = top
}

# DATE 
label {
    monitor = DP-1 
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = $fg
    font_size = 25
    font_family = $font
    position = -30, -150
    halign = right
    valign = top
}

# USER AVATAR
image {
    monitor = DP-1 
    path = ~/.face
    size = 100
    border_color = $green
    position = 0, 75
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor = DP-1
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $green
    inner_color = $bg-alt
    font_color = $fg
    fade_on_empty = false
    placeholder_text = 󰌾 Password
    hide_input = false
    check_color = $blue
    fail_color = $red
    fail_text = Wrong Password
    capslock_color = $yellow
    position = 0, -35
    halign = center
    valign = center
}

auth {
    fingerprint:enabled = true
}
