-- if true then
-- return {}
-- end -- WARN: REMOVE THIS LINE TO ACTIVATE THIS FILE

-- Customize Treesitter

-- ---@type LazySpec
-- return {
-- 	"nvim-treesitter/nvim-treesitter",
-- 	opts = {
-- 		ensure_installed = {
-- 			"lua",
-- 			"vim",
-- 			"yaml",
-- 			"zsh",
-- 			"bash",
-- 			"toml",
-- 			"python",
-- 			"terraform",
-- 			"go",
-- 			"templ",
-- 			"markdown",
-- 			"norg",
-- 			"html",
-- 			"latex",
-- 			"markdown_inline",
-- 			"neo-tree",
-- 			-- add more arguments for adding more treesitter parsers
-- 		},
-- 	},
-- }

-- return {
-- 	"nvim-treesitter/nvim-treesitter",
-- 	opts = function(_, opts)
-- 		-- Wyłączamy próby generowania gramatyk lokalnym CLI z Fedory
-- 		require("nvim-treesitter.install").prefer_git = false
-- 		require("nvim-treesitter.install").compilers = { "gcc", "clang" }
-- 	end,
-- }
